<a href="https://colab.research.google.com/github/divyea12/divyea12/blob/main/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [4]:
tensor_0_d = tf.constant(4)

In [5]:
print(tensor_0_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_1_d = tf.constant([2,0,-3,4.0])

In [7]:
print(tensor_1_d)

tf.Tensor([ 2.  0. -3.  4.], shape=(4,), dtype=float32)


In [8]:
tensor_2_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]

])
print(tensor_2_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [9]:
tensor_3_d = tf.constant([
  [[1,2,0],
   [2,3,-1]
  ],
  [
      [6,-2,3],
      [7,-8,9]
  ],
  [
      [0,1,2],
      [1,-2,3]
  ]
])
print(tensor_3_d)

tf.Tensor(
[[[ 1  2  0]
  [ 2  3 -1]]

 [[ 6 -2  3]
  [ 7 -8  9]]

 [[ 0  1  2]
  [ 1 -2  3]]], shape=(3, 2, 3), dtype=int32)


In [10]:
tensor_one_d = tf.constant([1,2.1,5],dtype = tf.float32)
print(tensor_one_d)

tf.Tensor([1.  2.1 5. ], shape=(3,), dtype=float32)


In [11]:
casted_tensor = tf.cast(tensor_one_d,dtype= tf.int16)
print(casted_tensor)

tf.Tensor([1 2 5], shape=(3,), dtype=int16)


In [12]:
casted_tensor = tf.cast(tf.constant([1,0,0],dtype = tf.int32), tf.bool)
print(casted_tensor)

tf.Tensor([ True False False], shape=(3,), dtype=bool)


In [13]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [14]:
tensor_string = tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [15]:
import numpy as np

In [16]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [17]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [18]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype= tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [19]:
filled_tensor = tf.fill(
    dims = [3,4,1],
    value = 5
)
print(filled_tensor)

tf.Tensor(
[[[5]
  [5]
  [5]
  [5]]

 [[5]
  [5]
  [5]
  [5]]

 [[5]
  [5]
  [5]
  [5]]], shape=(3, 4, 1), dtype=int32)


In [20]:
oned_tensor = tf.ones(
    [2,3],
)
print(oned_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [21]:
ones_like_tensor = tf.ones_like(filled_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]]], shape=(3, 4, 1), dtype=int32)


In [22]:
random_tensor = tf.random.normal(
    [3,2],
    mean =  100.0,
    stddev = 1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.45212   99.82384 ]
 [ 98.2284   102.119514]
 [ 99.81512  100.29827 ]], shape=(3, 2), dtype=float32)


In [23]:
uniform_tensor = tf.random.uniform(
    [3,2],
    minval=0,
    maxval = 1000,
    dtype = tf.dtypes.int32,
    seed = None,
    name = None
)
print(uniform_tensor)

tf.Tensor(
[[901 642]
 [517 907]
 [ 40 594]], shape=(3, 2), dtype=int32)


Indeing


In [24]:
tensor_indeed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indeed)

print(tensor_indeed[0:4])
print(tensor_indeed[1:6])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)


In [25]:
print(tensor_indeed[3:-2])

tf.Tensor([4 6], shape=(2,), dtype=int32)


In [26]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d[ 2, 0:])

tf.Tensor([1 5 6], shape=(3,), dtype=int32)


In [27]:
print(tensor_two_d[1:3,0])

tf.Tensor([3 1], shape=(2,), dtype=int32)


Maths


In [28]:
y = tf.constant([-2.15,3.25])
tf.abs(y)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.15, 3.25], dtype=float32)>

In [29]:
y1 = tf.constant([5,3,6,6,4,6],dtype = tf.int32)
y2 = tf.constant([7,6,2,6,7,11],dtype = tf.int32)
print(tf.math.add(y1,y2))


tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)


In [30]:
y1 = tf.constant([5,3,6,6,4,6],dtype = tf.int32)
y2 = tf.constant([7],dtype = tf.int32)
print(tf.add(y1,y2))


tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [31]:
y_argma = tf.constant([300,200,150,1000])
print(tf.math.argmax(y_argma))

tf.Tensor(3, shape=(), dtype=int64)


In [32]:
y_argma = tf.constant([
    [2,20,30,3,6],
    [3,11,16,1,8],
    [14,45,23,5,27]
])
print(tf.math.argmax(y_argma,1))

tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [33]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tf.math.reduce_sum(
    tensor_two_d,axis = None, keepdims = False,name =None
))


tf.Tensor(35, shape=(), dtype=int32)


In [34]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tf.math.reduce_max(
    tensor_two_d,axis = None, keepdims = False,name =None
))


tf.Tensor(8, shape=(), dtype=int32)


In [35]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tf.math.reduce_sum(
    tensor_two_d,axis = 0, keepdims = False,name =None
))


tf.Tensor([ 7 15 13], shape=(3,), dtype=int32)


In [36]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tf.math.reduce_sum(
    tensor_two_d,axis = 1, keepdims = False,name =None
))


tf.Tensor([ 3  7 12 13], shape=(4,), dtype=int32)


Linear Algebra Operations


In [38]:
import numpy as np

In [41]:
A = np.array([
  [2,6,5,2],
  [2,-2,2,3],
  [1,5,4,0]
])
B = np.array([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])
print(A.shape)
print(B.shape)
print(np.matmul(A,B),"\n")

print(np.einsum("ij,jk->ik",A,B))

(3, 4)
(4, 5)
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [48]:
A = np.array([
  [2,6,5,2],
  [2,-2,2,3],
  [1,5,4,0]
])
B = np.array([
    [2,9,0,3],
    [3,6,8,-2],
    [1,3,5,0]
])
print(A.shape,"\n", B.shape)
print(A*B,"\n")

print(np.einsum("ij,ij->ij",A,B))

(3, 4) 
 (3, 4)
[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [50]:
A = np.array([
    [[2,6,5,2],
        [2,-2,2,3],
        [1,5,4,0],
    ],
    [[1,3,1,22],
        [0,2,2,0],
        [1,5,4,1]
    ]
])
print(np.sum(A))

print(np.einsum('bij->',A))

72
72


Tensorflow functions
  

In [54]:
tensor_three_d = tf.constant([
     [[2,6,5,2],
        [2,-2,2,3],
        [1,5,4,0],
    ],
    [[1,3,1,22],
        [0,2,2,0],
        [1,5,4,1]
    ]
])
print(tensor_three_d.shape)

print(tf.expand_dims(tensor_three_d,axis = 0).shape)

(2, 3, 4)
(1, 2, 3, 4)


In [58]:
y = tf.constant([2,3,4,5])
print(y.shape)
print(tf.expand_dims(y,axis = 0))

(4,)
tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [59]:
y = tf.constant([[[2,3,4,5]]])
print(y.shape)
print(tf.squeeze(y,axis = 0))

(1, 1, 4)
tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [66]:
y_reshape = tf.constant([
    [3,5,6,6],
    [4,6,-1,2]
])
tf.reshape(y_reshape,[4,-1])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 6,  6],
       [ 4,  6],
       [-1,  2]], dtype=int32)>

Tensor Variables


In [68]:
y = tf.constant([1,2])
y_var = tf.Variable(y, name="Var1")
print(y_var)

<tf.Variable 'Var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [72]:
y_var.assign_add([10,16])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 0], dtype=int32)>

In [78]:
with tf.device('CPU:0'):
  y_var = tf.Variable(0.2)

print(y_var.device)

/job:localhost/replica:0/task:0/device:CPU:0
